"""deck foreign key

Revision ID: 4345e4437458
Revises: 61800c2e1b6c
Create Date: 2018-09-05 11:37:04.688280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4345e4437458'
down_revision = '61800c2e1b6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('deck_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'card', 'deck', ['deck_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_column('card', 'deck_id')
    # ### end Alembic commands ###
