"""
due dat

Revision ID: 46d4b157d052
Revises: 4345e4437458
Create Date: 2018-09-09 18:03:29.344386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46d4b157d052'
down_revision = '4345e4437458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_card_due_date'), 'card', ['due_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_due_date'), table_name='card')
    op.drop_column('card', 'due_date')
    # ### end Alembic commands ###
