"""deck table

Revision ID: 61800c2e1b6c
Revises: 80168d6ca60a
Create Date: 2018-09-05 11:34:28.368033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61800c2e1b6c'
down_revision = '80168d6ca60a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deck')
    # ### end Alembic commands ###
