"""added admin

Revision ID: 6aaa576add15
Revises: 22e0ce6e61de
Create Date: 2018-09-11 14:57:40.481546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aaa576add15'
down_revision = '22e0ce6e61de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ADMIN', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'ADMIN')
    # ### end Alembic commands ###
