"""empty message

Revision ID: 80057b364dc2
Revises: 
Create Date: 2018-09-04 13:41:14.462722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80057b364dc2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_index(op.f('ix_User_username'), 'User', ['username'], unique=True)
    op.create_table('Deck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Deck_name'), 'Deck', ['name'], unique=False)
    op.create_table('Card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('front', sa.String(length=1000), nullable=False),
    sa.Column('back', sa.String(length=1000), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('deck', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deck'], ['Deck.id'], ),
    sa.ForeignKeyConstraint(['owner'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Card')
    op.drop_index(op.f('ix_Deck_name'), table_name='Deck')
    op.drop_table('Deck')
    op.drop_index(op.f('ix_User_username'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###
