"""user, deck, and card tables

Revision ID: e5504cc002d1
Revises: 
Create Date: 2018-08-30 06:55:38.651590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5504cc002d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint("email ~ '\\A\\S+@\\S+\\.\\S+\\Z'::text", name='valid_email'),
    sa.CheckConstraint('length(username) > 0', name='blank_uname'),
    sa.PrimaryKeyConstraint('id', name='person_pkey'),
    sa.UniqueConstraint('email', name='person_email_key'),
    sa.UniqueConstraint('username', name='person_username_key')
    )
    # ### end Alembic commands ###
